### ISSUE TITLE
[JOSS review] cli argument --chdir not portable

### ISSUE THREAD

**Issue by mllg** [USCbiostats/sluRm#14]
This is a part of the JOSS review outlined in openjournals/joss-reviews#1493.

`--chdir` is not available for all slurm installations.

```
$ sbatch --version
slurm 16.05.9

$ sbatch --chdir=~
sbatch: unrecognized option '--chdir=~'
Try "sbatch --help" for more information
```
`-D` seems to be a workaround.

**Comment by gvegayon** [comment]
This actually turned to be a big issue (required me to make a new branch). I was kind of using `chdir` as a tmp_dir, now changed and it shouldn't be an issue anymore.
