### ISSUE TITLE
[JOSS review] Comparison table

### ISSUE THREAD

**Issue by mllg** [USCbiostats/sluRm#16]
This is a part of the JOSS review outlined in openjournals/joss-reviews#1493.

The comparison table in the readme says that `batchtools` cannot re-run jobs, but batchtools is perfectly capable of it:

```r
library(batchtools)
reg = makeRegistry(NA)
f = function(x) if (x == 3) stop(3) else x^2
btlapply(1:5, f, reg = reg)
# -> no result

# partial results are available in registry
reduceResultsList()

# re-submit failed jobs
# (job #3 will fail again of course, just for demonstration)
submitJobs(findErrors())
```

**Comment by gvegayon** [comment]
Didn't know that (nice feature! May hijack the concept/name for sluRm). As I said it before, the comparison table was built "to the best of my knowledge". More than happy to keep working on that. Sidenote, perhaps this can be a project of its own, like R4HPC or something. Not sure if there's something like that around, but perhaps having a git(hub) resource for general HPC with R may be useful (thoughts?).

**Comment by mllg** [comment]
> Sidenote, perhaps this can be a project of its own, like R4HPC or something. Not sure if there's something like that around, but perhaps having a git(hub) resource for general HPC with R may be useful (thoughts?).

I'm not aware of something like this. Might be a worthwhile endeavor.
