### ISSUE TITLE
[JOSS review] Prefer file.path()?

### ISSUE THREAD

**Issue by mllg** [USCbiostats/sluRm#17]
This is a part of the JOSS review outlined in openjournals/joss-reviews#1493.

This is nitpicking, but I'd suggest to use `file.path()` instead of `paste()` or `paste0()`. According to the documentation, `file.path()` should be faster.
Feel free to just close this issue if you disagree or have other reasons to not use `file.path()`.

**Comment by gvegayon** [comment]
Overall, to build filepaths I use `sprintf` which is about the same as `file.path`. I do this in the function `snames` which is a general wrapper. I do see that I was still using `paste` in some places. Just changed that (thanks!)
