### ISSUE TITLE
Reverse

### ISSUE THREAD

**Issue by amiloudij** [USCbiostats/sluRm#38]
Hello, I have to files. One file is .sh extensions containting slurm script and a job array of 1000. The another file is a r script that use SLURM_TASK_ARRAY_ID as a seed and it will be used in whole script.
Since i am a mac user and I dont have SLURM installed, and I want to only use the package slurmR.
I am a asking about the way i can get the 
SLURM_TASK_ARRAY_ID using only SlurmR in rstudio. If it is possible, I can run my 1000 jobs.

Thank you

**Comment by gvegayon** [comment]
Seems like a feature request. It's been close to a year now and I don't have enough time to add more functionality. I'll close this with a tag indicating that this is a feature request. Feel free to re-open if you feel like submitting a PR. Thanks!
